ournft_site/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/',login_required(views.logout_view,login_url='home'), name='logout'),
    path('profile/', login_required(views.profile_view.as_view(), login_url='home'), name='profile'),
    path('profile/edit/', login_required(views.EditProfileView.as_view(),login_url='home'), name='edit_profile'),
    path('set_avatar/<slug:image_hash>', views.SetAvatar, name='set_avatar')
  
]

ournft_site/ournft_site/urls.py
from django.contrib import admin
from django.urls import path, include
from ournft_app import views

urlpatterns = [

    path('', views.home.as_view(), name='home'),

    path('admin/', admin.site.urls),

    path('', include('ournft_app.urls')),
  
    path('accounts/', include('accounts.urls')),

    path('captcha/', include("captcha.urls"))

]

from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

ournft_site/ournft_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Count
import imagehash
import uuid
from ckeditor.fields import RichTextField
# from django.contrib.auth import get_user_model

# User = get_user_model()
# Create your models here.
DIFF_THRESHOLD = 0.2

def image_path(instance, filename):
    return f'images/{instance.image_hash}.png'

def diff(hash1, hash2):
    q1 = bin(int(hash1,16))[2:]
    q2 = bin(int(hash2,16))[2:]
    hamm_dist = len([1 for i,j in zip(q1,q2) if i!=j])
    print(hamm_dist/len(q1))
    return hamm_dist/len(q1)


class PublicImageManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(visibility=True)

class Image(models.Model):

    upload_datetime = models.DateTimeField(verbose_name="Date", auto_now_add=True)
    image = models.ImageField(upload_to=image_path,verbose_name="Image")
    image_hash = models.CharField(max_length=64,verbose_name="Token", null=False)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Owner", related_name="images")
    text = models.CharField(max_length=200, verbose_name="Text", null=True, blank=True)
    visibility = models.BooleanField(verbose_name="Visible", null=False)
    secret = models.CharField(max_length=50,verbose_name="Secret", null=False)
    banned = models.BooleanField(verbose_name="Banned", default=False, null=False)
    likes = models.ManyToManyField(User, related_name="likes", blank=True)


    objects = models.Manager()
    public = PublicImageManager()
    

    def save(self, *args, **kwargs):
        if self.pk is None:
            print("create image object")
        else:
            print("change image object")
        super().save(*args, **kwargs)

    class Meta:
        ordering = ["-upload_datetime"]

    def __str__(self):
        return str(self.image_hash)

    def GetImageHash(image):
        return f'{imagehash.phash(imagehash.Image.open(image))}'

    def IsUnique(image_hash):
        query = Image.objects.values_list('image_hash')
        return not [i[0] for i in query if diff(i[0], image_hash) < DIFF_THRESHOLD]
    
    def total_likes(self):
        return self.likes.count()

    def most_liked():
        return Image.public.annotate(num_likes=Count('likes')).order_by('-num_likes')


class History(models.Model):
    datetime = models.DateTimeField(verbose_name="Date", auto_now_add=True)
    referred_owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Owner", related_name="record")
    referred_image = models.ForeignKey(Image, on_delete=models.CASCADE, verbose_name="Image", related_name="record")

    def of_image(image):
        return History.objects.filter(referred_image=image)


class Notification(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="New Owner", related_name="notifications")
    new_image = models.ForeignKey(Image, on_delete=models.CASCADE, verbose_name="New Image", related_name="notifications")

class Comment(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(User,on_delete=models.CASCADE, verbose_name="User", related_name="comments")
    image = models.ForeignKey(Image,on_delete=models.CASCADE, verbose_name="Image", related_name="comments")
    content = RichTextField(blank=True, null=True)

class Report(models.Model):
    link = models.URLField(verbose_name='Link', null=False, blank=False, max_length=50)
    text = models.TextField(verbose_name='Text', null=False, blank='True', max_length='500')

ournft_site/ournft_app/forms.py
from django import forms

from .models import Image, Comment, Report

from captcha.fields import CaptchaField
from django.contrib.auth.models import User
from django.utils.html import format_html


class ImageChoiceField(forms.ModelChoiceField):

    def label_from_instance(self, obj):
        return format_html('<img src="{}" alt="connect" style="max-height:80px">', obj.image.url)  

class ImageForm(forms.ModelForm):
    """Form for the image model"""
    class Meta:
        model = Image
        fields = ['image', 'text', 'visibility']


class RestoreImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['image', 'secret']
    
class CaptchaForm(forms.Form):
    captcha = CaptchaField()

class TransferForm(forms.Form):
    recipient = forms.ModelChoiceField(queryset = User.objects.none(), label="Give to")
    image_hash = ImageChoiceField(queryset = Image.objects.none(),label="Image",widget=forms.RadioSelect)

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(TransferForm, self).__init__(*args, **kwargs)
        if user:
            self.fields['recipient'].queryset = User.objects.exclude(pk = user.pk).exclude(username='AnonymousUser')
            self.fields['image_hash'].queryset = Image.objects.filter(owner=user)
        
        
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content',]

class ReportForm(forms.ModelForm):
    class Meta:
        model= Report
        fields = ['link','text']

class BanUserForm(forms.Form):
    user = forms.ModelChoiceField(queryset = User.objects.none(), label="Ban user")
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(BanUserForm, self).__init__(*args, **kwargs)
        if user:
            self.fields['user'].queryset = User.objects.exclude(pk = user.pk).exclude(username='AnonymousUser').filter(is_staff=False)

class TokenRestoreForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['image_hash', 'secret']

class ModerTokenRestoreForm(forms.ModelForm):

    user = forms.ModelChoiceField(queryset = User.objects.exclude(username='AnonymousUser'), label="User")
    
    class Meta:
        model = Image
        fields = ['image_hash', 'secret']
    

ournft_site/templates/ban_user.html
{% extends "base.html" %} 

{% block content %}

<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">Update</button>
</form>

{% if accepted %}
    {% if banned %}
        <h3>Succesfully banned {{username}}!</h3>
    {% else %}
        <h3>Succesfully unbanned {{username}}!</h3>   
    {% endif %}
{% endif %}

{% endblock content %}

ournft_site/templates/base.html
<!doctype html>
<html lang="en">
<head>
	<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
		<!-- /* .sidenav {
			height:100%;
			width:160px;
			position: fixed;
			z-index:1;
			top:0;
			left:0;
			background-color:#111;
			overflow-x:hidden;
			padding-top:20px;
		}
 
		.sidenav a {
			padding:6px 8px 6px 16px;
			text-decoration: none;
			font-size:25px;
			color: #818181;
			display:block;
		}
 
		.sidenav a:hover{
			color:#f1f1f1;
		}	
 
		.main{
			margin-left:160px;
			padding: 0px 10px;
		} */ -->
 
    <meta charset="utf-8">

    <title>Our NFT</title>
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		<div class="container-fluid">
		  <a class="navbar-brand" href="/">OurNFT</a>
		  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		  </button>
	  
		  <div class="collapse navbar-collapse" id="navbarColor02">
			<ul class="navbar-nav me-auto">
				<li class="nav-item">
					<a class="nav-link" href="/">Home</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="/transfer">Transfer Image</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="/accounts/profile">Profile</a>
				</li>
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Restore</a>
          			<div class="dropdown-menu">
						<a class="dropdown-item" href="/restore">Image Restore</a>
						<a class="dropdown-item" href="/token_restore">Token Restore</a>
					</div>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="/feed">Image Feed</a>
				</li>
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Report</a>
          			<div class="dropdown-menu">
						{% load report_tag %}
						<form method="post" action="{% url 'report'%}" enctype="multipart/form-data" >
							<input type="hidden" name="next" value="{{ request.path }}">
							{% csrf_token %}
							{% report_form %}
							<button type="submit">Upload</button>
						</form>
					</div>
				</li>
				{% if request.user.is_staff %}
				<li class="nav-item">
					<a class="nav-link" href="/report_list">Reports</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="/ban_user">Ban User</a>
				</li>
				{% endif %}
			</ul>
			<form class="d-flex" action="{% url 'accounts:logout' %}" method="post">
				{% csrf_token %}
				<button class="btn btn-secondary my-2 my-sm-0 me-sm-2" type="submit">Log Out</button>
			</form>
		  </div>
		</div>
	  </nav>

    <div id="content", class="main">
        {% block content %}{% endblock content %}
    </div>
</body>
</html>

ournft_site/templates/comment.html
<form action="{% url 'comment' image.image_hash %}" method='POST'>
    <input type="hidden" name="next" value="{{ request.path }}">
    {% csrf_token %}
    {{ new_comment.media }}
    <p> Add comment: </p>
    <p> {{ new_comment.content }} </p>
    <button type="submit">Comment</button>
</form>

ournft_site/templates/edit_profile.html
{% extends "base.html" %} 
{% load static %}
{% block content %}

<div class="container content" style="text-align: center;">
    <div style="display: inline-block; width: 400px;">
        <h2>Edit profile</h2>
        <form method="post" class="bootstrap-form" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-success" value="Save">
        </form>
    </div>
</div>
<div style="display: inline-block; width: 400px;">
    <h2>Set Avatar</h2>
    {% for image in images %}
        <div class="card">
            <div class="card-body">
                {% if image.image.name %}
                <a href="/images/{{image.image_hash}}">
                    <img src="{{ image.image.url }}" alt="connect" style="max-height:300px"><br>
                </a>
                {% endif %}
                {{ image.text }}
                {% include "set_avatar.html" %}
            </div>
        </div>
        
    {% endfor %}
</div>


{% endblock content %}

ournft_site/templates/home.html
{% extends "base.html" %} 
{% block content %}
<nav class="mb-3">
    {% if user.is_authenticated %}
        <form action="{% url 'accounts:logout' %}" method="post">
            {% csrf_token %}
            <button class="btn btn-primary btn-sm" type="submit">Log Out</button>
        </form>

        <form action="{% url 'accounts:profile' %}" method="get">
            <button class="btn btn-primary btn-sm" type="submit">Profile</button>
        </form>

    {% else %}
    <form action="{% url 'accounts:login' %}" method="get">
        <button class="btn btn-primary btn-sm" type="submit">Log In</button>
    </form>

    <form action="{% url 'accounts:signup' %}" method="get">
        <button class="btn btn-primary btn-sm" type="submit">Signup</button>
    </form>
    {% endif %}
</nav>
{% endblock content %}

ournft_site/templates/image.html
{% extends "base.html" %}

{% block content %}

{% if image %}
<img src="{{image.image.url}}" alt="connect" style="max-height:300px">
{% if request.user.is_staff %}
<form action="{% url 'ban_image' image.image_hash  %}" method='POST'>
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ request.path }}">
    <button type="submit" class="btn btn-danger">Ban</button>
</form>
{% endif %}
<h3> Description: {{image.text}} </h3>
<h3> Current owner: {{image.owner}} </h3>
<h3> Uploaded: {{image.upload_datetime}} </h3>
<h3> Visible: {{image.visibility}} </h3>
{% if not image.banned and image.owner == request.user %}
<form action="{% url 'switch_visibility' image.image_hash  %}" method='POST'>
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ request.path }}">
    {% if image.visibility %}
        <button type="submit" class="button">Make Private</button>
    {% else %}
        <button type="submit" class="button">Make Public</button>
    {% endif %}
</form>
{% endif %}
{% include "likes.html" %}
<h3> Liked: {% for user in image.likes.all %} {{user}}; {% endfor %} </h3>
<div class="history">
    <h3> History of ownership: </h3>
    {% for record in history %}
    <div class="card">
        <div class="card-body">
            {% if record %}
            Owner: {{record.referred_owner}}; Since: {{record.datetime}}
            {% endif %}
        </div>
    </div>
    {% endfor %}
</div>

<div class="comments">
    {% load comment_filter %}
    {% for comment in comments %}
    <div class="card">
        {{comment.user.username}}
        <img src="{{comment.user.profile.avatar.image.url}}" alt="connect" style="max-height:20px"> :
        {{ comment.content|safe_comment }}
        {% if request.user.is_staff %}
        <form action="{% url 'delete_comment' comment.id  %}" method='POST'>
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ request.path }}">
            <button type="submit">Delete</button>
        </form>
        {% endif %}
    </div>
    {% endfor %}
    <div class="new-comment">
        {% include "comment.html" %}
    </div>
</div>
{% endif %}

{% endblock content %}

ournft_site/templates/index.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
</form>
  
{% if img_obj %}
  {% if is_unique == True %}
    <h3>Succesfully uploaded :</h3>
    <img src="{{ img_obj.image.url}}" alt="connect" style="max-height:300px">
  {% else %}
    <h3>Image is not unique</h3>
  {% endif %}
{% endif %}

ournft_site/templates/profile.html
{% extends "base.html" %} 
{% load static %}

{% block content %}
<div class="container content">
    <h2>My profile</h2>
</div>


<div class="container content">
    <h2>{{ selected_user.get_full_name }}</h2>

    <div class="row" style="margin-left: 20px;">
        <div class="col5">
            {% if user.profile.avatar %}
                <br>
                    <img src="{{ user.profile.avatar.image.url }}" alt="connect" style="max-height:300px"><br>
                <br>
            {% endif %}
            {% for notification in notifications %}
                <p>
                    <a href="{% url 'notification' notification.id %}">
                        <button class="button"> You got new image! See it: </button>
                    </a>
                </p>
            {% endfor %}
        </div>
        <div class="col">
            <dl class="row">
                <dt class="col-sm-3 text-right">Name</dt>
                <dd class="col-sm-9">{{ selected_user.username }}</dd>


                <dt class="col-sm-3 text-right">Info</dt>
                <dd class="col-sm-9"><em style="font-family: 'Times New Roman', serif;">{{ selected_user.profile.bio|linebreaks }}</em></dd>
            </dl>
        </div>
        {% if selected_user.id == user.id %}
            <form action="{% url 'accounts:edit_profile' %}" method="get">
                <button class="btn btn-primary btn-sm" type="submit">Edit</button>
            </form>
        {% endif %}
    </div>
</div>

{% endblock content %}

ournft_site/templates/report_list.html
{% extends "base.html" %} 

{% block content %}

<h1> Reports: </h1>
{% for report in reports %}
<div class="card">
    <div>
        <a href="{{report.link}}" target="_blank" rel="noopener noreferrer">{{report.link}}</a>
    </div>
    <div>
        {{report.text}}
    </div>
</div>
{% endfor %}

{% endblock content %}

ournft_site/templates/restore.html
{% extends "base.html" %} 

{% block content %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
</form>
{% if asked %}
  {% if accepted %}
    <h3>Succesfully restored!</h3>
    {% if not request.user.is_staff%}
    <h3>New secret token(save it!!): {{secret}}</h3>
    {% endif %}
    {% if image %}
      <img src="{{ image.url}}" alt="connect" style="max-height:300px">
    {% endif %}
  {% else %}
    <h3>Wrong image or secret</h3>
  {% endif %}
{% endif %}

{% endblock content %}

ournft_site/templates/set_avatar.html
<form action="{% url 'accounts:set_avatar' image.image_hash %}" method='POST' class="ui form">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ request.path }}">
    {% if user.profile.avatar == image %}
      <button class="ui button discard" type='submit'> Discard Avatar </button>
    {% else%}
      <button class="ui button set" type='submit'> Set Avatar </button>
    {% endif %}
</form>

ournft_site/templates/signup.html
{% extends "base.html" %} 
{% load static %}

{% block content %}
    <h1>Signup</h1>
    <form action="/accounts/signup/" method="post">
        {% csrf_token %}
        {{ form }}
        {{ form_captcha }}
        <input type="submit" value="Signup">
    </form>
    
{% endblock content %}

ournft_site/templates/timeline.html
{% extends "base.html" %} 

{% block content %}

<div class="col-6 content">
  {% if request.user.profile.banned %}
  <h3>You are banned!</h3>
  {% else %}
  <div class="card">
    <div class="card-body">
      <form method="post" name="new-post-form" enctype="multipart/form-data">
        {% csrf_token %} {{ form.as_p }}
        <button type="submit">Upload</button>
      </form>
    </div>
  </div>
  <br />
  {% if form_obj %} {% if is_unique %}
  <h3>Succesfully uploaded! Token: {{form_obj.image_hash}}</h3>
  <h3>Secret to restore image(save it): {{form_obj.secret}}</h3>
  {% else %}
  <h3>Image is not unique</h3>
  {% endif %} {% endif %}
  <br />
  {% endif %}
  <div class="timeline">
    {% for image in images %}
    <div class="card">
      <div class="card-body">
        {% if image.image.name %}
        <a href="/images/{{image.image_hash}}">
          <img
            src="{{ image.image.url }}"
            alt="connect"
            style="max-height: 300px"
          /><br />
        </a>
        {% endif %} {{ image.text }} {% include "likes.html" %}
      </div>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock content %}

ournft_site/templates/transfer.html
{% extends "accounts/layout/base.html" %} 

{% block content %}

<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <!-- <p>
    <label for="id_recipient">Give to:</label>
    <select name="recipient" required id="id_recipient">
      {% for id, username in form.fields.recipient.choices %}
        <option value="{{id}}">{{username}}</option>
      {% endfor %}
    </select>
 </p>
  <p>
    <label for="id_image_hash">Image:</label>
    <select name="image_hash" required id="id_image_hash">
      {% for pk, image in form.fields.image_hash.choices %}
        <option value="{{pk}}"><img src="{{image.image.url}}" alt="connect" style="max-height:300px"></option>
      {% endfor %}
    </select>
  </p> -->
  <button type="submit">Upload</button>
</form>

{% if accepted %}
  <h3>Succesfully transferred!</h3>
  {% if image %}
    <img src="{{ image.url }}" alt="connect" style="max-height:300px">
  {% endif %}
{% endif %}

{% endblock content %}